// Generated by scripts/gen-types.mjs from src/onchain.js. Do not edit by hand; run `npm run types`.
export function tfetch(url: string, opts?: {}, ms?: number): Promise<Response>;
export function rpc(chain: Chain, method: string, params?: any[]): Promise<any>;
export function prices(ids: string[]): Promise<{}>;
export function evmFees(chain: Chain): Promise<{
    chain: any;
    gasPriceWei: bigint;
}>;
export function feeCost(f: { baseFeeWei?: bigint; tipWei?: Record<string, bigint>; gasPriceWei?: bigint }, gasUnits: string | number | bigint, tier?: string): {
    perGasWei: any;
    totalWei: bigint;
};
export function btcFees(): Promise<any>;
export function solFees(): Promise<{
    baseLamportsPerSignature: number;
    priorityMicroLamportsPerCU: {
        p50: any;
        p75: any;
        p90: any;
    };
    samples: any;
}>;
export function convertUnits(value: string | number, from: keyof typeof UNITS): {
    _hex: string;
};
export function normSig(sig: string): string;
export function encodeCall(sig: string, args: unknown[]): string;
export function lookupSelector(sel: string): Promise<any[]>;
export function lookupEvent(topic0: string): Promise<any>;
export function decodeCalldata(data: string, sigHint?: string): Promise<{
    selector: any;
    note: string;
    signature?: undefined;
    args?: undefined;
    candidates?: undefined;
} | {
    selector: any;
    signature: string;
    args: {
        name: string;
        type: string;
        value: any;
    }[];
    candidates: any[];
    note?: undefined;
} | {
    selector: any;
    signature: any;
    candidates: any[];
    note: string;
    args?: undefined;
}>;
export function checkAddress(a: string): {
    valid: boolean;
    checksum?: undefined;
    inputChecksumValid?: undefined;
} | {
    valid: boolean;
    checksum: string;
    inputChecksumValid: boolean;
};
export function mainnetProvider(): any;
export function resolveEns(name: string): Promise<any>;
export function reverseEns(addr: string): Promise<any>;
export function addressInfo(chain: Chain, addr: string): Promise<{
    chain: any;
    balanceWei: bigint;
    isContract: boolean;
    codeBytes: number;
    nonce: number;
}>;
export function erc20Meta(chain: Chain, token: string): Promise<{
    name: any;
    symbol: any;
    decimals: number;
    totalSupply: string;
}>;
export function decodeTx(chain: Chain, hash: string): Promise<{
    chain: any;
    hash: any;
    from: any;
    to: any;
    valueWei: bigint;
    nonce: number;
    type: number;
    block: number;
    input: any;
}>;
export function hashes(input: string, mode?: string): {
    keccak256: string;
    sha256: string;
    ripemd160: string;
    bytes: number;
};
export function merkleStandard(types: string[], rows: unknown[][]): {
    root: string;
    proofs: any;
    dump: import("@openzeppelin/merkle-tree/dist/standard.js").StandardMerkleTreeData<any[]>;
};
export function merkleSimple(leaves: string[]): {
    root: string;
    proofs: any;
};
export function mappingSlot(keyType: string, key: unknown, slot: string | number | bigint): string;
export function nestedMappingSlot(keys: [keyType: string, key: unknown][], slot: string | number | bigint): string;
export function arrayElementSlot(slot: string | number | bigint, index: string | number | bigint, elemSlots?: number): string;
export function erc7201Slot(id: string): string;
export function readSlot(chain: Chain, address: string, slot: string | number | bigint): Promise<any>;
export function dataset(name: string): Promise<any>;
export function tokenList(): Promise<any>;
export const API: "https://blockchains.github.io/blockchainlab-api/v1";
export const SITE: "https://blockchainlab.com";
export function utm(path: string, tool: string): string;
export namespace CHAINS {
    namespace ethereum {
        let id: number;
        let name: string;
        let symbol: string;
        let gecko: string;
        let rpcs: string[];
        let explorer: string;
    }
    namespace base {
        let id_1: number;
        export { id_1 as id };
        let name_1: string;
        export { name_1 as name };
        let symbol_1: string;
        export { symbol_1 as symbol };
        let gecko_1: string;
        export { gecko_1 as gecko };
        let rpcs_1: string[];
        export { rpcs_1 as rpcs };
        let explorer_1: string;
        export { explorer_1 as explorer };
        export let l2: boolean;
    }
    namespace arbitrum {
        let id_2: number;
        export { id_2 as id };
        let name_2: string;
        export { name_2 as name };
        let symbol_2: string;
        export { symbol_2 as symbol };
        let gecko_2: string;
        export { gecko_2 as gecko };
        let rpcs_2: string[];
        export { rpcs_2 as rpcs };
        let explorer_2: string;
        export { explorer_2 as explorer };
        let l2_1: boolean;
        export { l2_1 as l2 };
    }
    namespace optimism {
        let id_3: number;
        export { id_3 as id };
        let name_3: string;
        export { name_3 as name };
        let symbol_3: string;
        export { symbol_3 as symbol };
        let gecko_3: string;
        export { gecko_3 as gecko };
        let rpcs_3: string[];
        export { rpcs_3 as rpcs };
        let explorer_3: string;
        export { explorer_3 as explorer };
        let l2_2: boolean;
        export { l2_2 as l2 };
    }
    namespace polygon {
        let id_4: number;
        export { id_4 as id };
        let name_4: string;
        export { name_4 as name };
        let symbol_4: string;
        export { symbol_4 as symbol };
        let gecko_4: string;
        export { gecko_4 as gecko };
        let rpcs_4: string[];
        export { rpcs_4 as rpcs };
        let explorer_4: string;
        export { explorer_4 as explorer };
    }
    namespace bsc {
        let id_5: number;
        export { id_5 as id };
        let name_5: string;
        export { name_5 as name };
        let symbol_5: string;
        export { symbol_5 as symbol };
        let gecko_5: string;
        export { gecko_5 as gecko };
        let rpcs_5: string[];
        export { rpcs_5 as rpcs };
        let explorer_5: string;
        export { explorer_5 as explorer };
    }
    namespace avalanche {
        let id_6: number;
        export { id_6 as id };
        let name_6: string;
        export { name_6 as name };
        let symbol_6: string;
        export { symbol_6 as symbol };
        let gecko_6: string;
        export { gecko_6 as gecko };
        let rpcs_6: string[];
        export { rpcs_6 as rpcs };
        let explorer_6: string;
        export { explorer_6 as explorer };
    }
}
export function chainById(id: number | string): string;
export const SOL_HOT_ACCOUNTS: string[];
export namespace UNITS {
    let wei: number;
    let kwei: number;
    let mwei: number;
    let gwei: number;
    let szabo: number;
    let finney: number;
    let ether: number;
    let sat: number;
    let btc: number;
    let lamport: number;
    let sol: number;
}
export function selector(sig: string): string;
export function topic(sig: string): string;
export namespace EIP1967 {
    let implementation: string;
    let admin: string;
    let beacon: string;
}
export { ethers };
import { ethers } from "ethers";

/** EVM chains supported by the live tools (keys of CHAINS). */
export type Chain = keyof typeof CHAINS;
