// Generated by scripts/gen-types.mjs from src/onchain2.js. Do not edit by hand; run `npm run types`.
import type { Chain } from "./onchain.js";
export function multicall(chain: Chain, calls: { target: string; data: string }[]): Promise<any>;
export function safeTx(p: SafeTxInput): {
    to: string;
    value: bigint;
    data: any;
    operation: number;
    safeTxGas: bigint;
    baseGas: bigint;
    gasPrice: bigint;
    gasToken: any;
    refundReceiver: any;
    nonce: bigint;
};
export function safeTxHash(chainId: number | bigint, safe: string, tx: SafeTx, version?: string): {
    safeTxHash: string;
    domainSeparator: string;
    messageHash: string;
};
export function safeInfo(chain: Chain, safe: string): Promise<{
    chain: any;
    safe: string;
    owners: any[];
    threshold: number;
    nonce: number;
    version: any;
}>;
export function safeTxHashOnchain(chain: Chain, safe: string, tx: SafeTx): Promise<any>;
export function encodeMultiSend(txs: MultiSendTx[]): string;
export function decodeMultiSend(calldata: string): {
    operation: number;
    to: string;
    value: bigint;
    data: string;
}[];
export function decodeSafeCalldata(data: string): any;
export function typedDataHash(td: TypedData): {
    digest: string;
    domainSeparator: string;
    structHash: string;
    primaryType: string;
};
export function signTypedData(privateKey: string, td: TypedData): Promise<{
    signer: string;
    signature: string;
}>;
export function recoverTypedData(td: TypedData, signature: string): string;
export function erc1271(chain: Chain, contract: string, digest: string, signature: string): Promise<{
    magic: any;
    valid: boolean;
    error?: undefined;
} | {
    valid: boolean;
    error: any;
    magic?: undefined;
}>;
export function calldataDiff(a: string, b: string, sigHint?: string): Promise<{
    a: {
        selector: any;
        note: string;
        signature?: undefined;
        args?: undefined;
        candidates?: undefined;
    } | {
        selector: any;
        signature: string;
        args: {
            name: string;
            type: string;
            value: any;
        }[];
        candidates: any[];
        note?: undefined;
    } | {
        selector: any;
        signature: any;
        candidates: any[];
        note: string;
        args?: undefined;
    };
    b: {
        selector: any;
        note: string;
        signature?: undefined;
        args?: undefined;
        candidates?: undefined;
    } | {
        selector: any;
        signature: string;
        args: {
            name: string;
            type: string;
            value: any;
        }[];
        candidates: any[];
        note?: undefined;
    } | {
        selector: any;
        signature: any;
        candidates: any[];
        note: string;
        args?: undefined;
    };
    sameFunction: boolean;
    rows: {
        field: string;
        a: any;
        b: any;
        same: boolean;
    }[];
    changed: number;
    wordDiff: {
        word: string | number;
        a: any;
        b: any;
        same: boolean;
    }[];
}>;
export function verification(chain: Chain, address: string): Promise<{
    chain: any;
    address: any;
    sourcify: any;
    blockscout: any;
}>;
export function gasHistory(chain: Chain, blocks?: number): Promise<{
    chain: any;
    from: number;
    to: number;
    points: any;
    stats: {
        min: any;
        p25: any;
        median: any;
        p75: any;
        max: any;
        nextBaseFeeGwei: number;
    };
}>;
export function sparkSVG(values: (number | null)[], w?: number, h?: number, color?: string): string;
export function bridgeQuotes({ from, to, asset, amount, user }: {
    from: any;
    to: any;
    asset?: string;
    amount: any;
    user?: string;
}): Promise<{
    from: any;
    to: any;
    asset: string;
    amount: number;
    quotes: any[];
}>;
export function approvals(chain: Chain, owner: string, tokens: { address: string; symbol?: string; decimals?: number }[]): Promise<{
    chain: any;
    owner: any;
    checkedTokens: any;
    checkedSpenders: number;
    approvals: any[];
    revokeCash: string;
}>;
export function allowanceOf(chain: Chain, token: string, owner: string, spender: string): Promise<bigint>;
export function ensBulk(names: string[], { texts }?: {
    texts?: string[];
}): Promise<any[]>;
export function solRpc(method: string, params: unknown[]): Promise<any>;
export function decodeSolTx(sig: string): Promise<{
    signature: any;
    slot: any;
    blockTime: string;
    status: string;
    error: any;
    feeSOL: number;
    computeUnits: any;
    version: any;
    signers: any;
    instructions: any;
    innerInstructions: any;
    solChanges: any;
    tokenChanges: any[];
    logs: any;
}>;
export function decodePSBT(input: string): {
    kind: string;
    version: number;
    locktime: number;
    inputs: {
        txid: string;
        vout: number;
        sequence: number;
        value: any;
        address: string;
        type: "p2a" | "pk" | "pkh" | "sh" | "wsh" | "wpkh" | "ms" | "tr" | "tr_ns" | "tr_ms" | "unknown";
        partialSigs: number;
        finalized: boolean;
        bip32: {
            pubkey: string;
            fingerprint: string;
            path: string;
        }[];
    }[];
    outputs: {
        value: bigint;
        address: string;
        type: "p2a" | "pk" | "pkh" | "sh" | "wsh" | "wpkh" | "ms" | "tr" | "tr_ns" | "tr_ms" | "unknown";
        script: string;
    }[];
    inputTotal: bigint;
    outputTotal: bigint;
    feeSats: bigint;
    vsize: number;
    feeRate: number;
    isFinal: boolean;
    txid: string;
};
export function addressLabels(chain: Chain, address: string): Promise<{
    chain: any;
    address: any;
    labels: any[];
}>;
export function vanityDifficulty(pattern: string, { caseSensitive, position }?: {
    caseSensitive?: boolean;
    position?: string;
}): {
    pattern: any;
    difficulty: number;
    attempts50: number;
    attempts90: number;
};
export function vanityBenchmark(ms?: number): number;
export function priceImpact(chain: UniV3Chain, tokenIn: string, tokenOut: string, amountIn: string, fee?: number): Promise<{
    chain: any;
    pool: any;
    fee: number;
    tokenIn: any;
    tokenOut: any;
    amountIn: number;
    amountOut: number;
    midPrice: number;
    execPrice: number;
    priceImpactPct: number;
    totalCostVsMidPct: number;
    priceAfter: number;
    ticksCrossed: number;
    gasEstimate: number;
}>;
export function sandwichCheck(chain: Chain, hash: string): Promise<{
    chain: any;
    hash: any;
    block: number;
    index: number;
    blockTxs: any;
    swapsInTx: any;
    sandwiched: boolean;
    evidence: {
        pool: any;
        front: {
            hash: any;
            index: any;
            from: any;
            to: any;
        };
        back: {
            hash: any;
            index: any;
            from: any;
            to: any;
        };
    };
    candidates: number;
    method: string;
}>;
export function findSandwiches(chain: Chain, blockNumber: number | bigint): Promise<{
    victim: any;
    front: any;
    pool: any;
}[]>;
export function stablecoins(): Promise<any>;
export function rpcHealth(chain: Chain, urls?: string[]): Promise<{
    chain: any;
    head: number;
    endpoints: any[];
}>;
export const MULTICALL3: "0xcA11bde05977b3631167028862bE2a173976CA11";
export namespace SAFE_TX_TYPES {
    let SafeTx: {
        name: string;
        type: string;
    }[];
}
export function recoverPersonal(message: string, signature: string): string;
export namespace EIP712_MAIL_EXAMPLE {
    namespace types {
        let EIP712Domain: {
            name: string;
            type: string;
        }[];
        let Person: {
            name: string;
            type: string;
        }[];
        let Mail: {
            name: string;
            type: string;
        }[];
    }
    let primaryType: string;
    namespace domain {
        let name: string;
        let version: string;
        let chainId: number;
        let verifyingContract: string;
    }
    namespace message {
        namespace from {
            let name_1: string;
            export { name_1 as name };
            export let wallet: string;
        }
        namespace to {
            let name_2: string;
            export { name_2 as name };
            let wallet_1: string;
            export { wallet_1 as wallet };
        }
        let contents: string;
    }
}
export namespace BLOCKSCOUT {
    let ethereum: string;
    let base: string;
    let arbitrum: string;
    let optimism: string;
    let polygon: string;
}
export namespace USDC {
    let ethereum_1: string;
    export { ethereum_1 as ethereum };
    let base_1: string;
    export { base_1 as base };
    let arbitrum_1: string;
    export { arbitrum_1 as arbitrum };
    let optimism_1: string;
    export { optimism_1 as optimism };
    let polygon_1: string;
    export { polygon_1 as polygon };
}
export namespace WETH {
    let ethereum_2: string;
    export { ethereum_2 as ethereum };
    let base_2: string;
    export { base_2 as base };
    let arbitrum_2: string;
    export { arbitrum_2 as arbitrum };
    let optimism_2: string;
    export { optimism_2 as optimism };
    let polygon_2: string;
    export { polygon_2 as polygon };
}
export const SPENDERS: {
    "0x000000000022D473030F116dDEE9F6B43aC78BA3": string;
    "0x66a9893cC07D91D95644AEDD05D03f95e1dBA8Af": string;
    "0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD": string;
    "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45": string;
    "0xE592427A0AEce92De3Edee1F18E0157C05861564": string;
    "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D": string;
    "0x111111125421cA6dc452d289314280a0f8842A65": string;
    "0x1111111254EEB25477B68fb85Ed929f73A960582": string;
    "0xDef1C0ded9bec7F1a1670819833240f027b25EfF": string;
    "0xC92E8bdf79f0507f65a392b0ab4667716BFE0110": string;
    "0xBA12222222228d8Ba445958a75a0704d566BF2C8": string;
    "0x1E0049783F008A0085193E00003D00cd54003c71": string;
    "0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2": string;
    "0x6131B5fae19EA4f9D964eAc0408E4408b66337b5": string;
    "0x6A000F20005980200259B80c5102003040001068": string;
};
export const SOL_RPC: string[];
export const SOL_PROGRAMS: {
    "11111111111111111111111111111111": string;
    TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA: string;
    TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb: string;
    ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL: string;
    ComputeBudget111111111111111111111111111111: string;
    JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4: string;
    whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc: string;
    "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8": string;
    CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK: string;
    LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo: string;
    MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr: string;
    "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P": string;
    Vote111111111111111111111111111111111111111: string;
    Stake11111111111111111111111111111111111111: string;
    metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s: string;
};
export function create2Address(deployer: string, salt: string, initCode: string): string;
export namespace UNIV3 {
    export namespace ethereum_3 {
        let factory: string;
        let quoter: string;
    }
    export { ethereum_3 as ethereum };
    export namespace arbitrum_3 {
        let factory_1: string;
        export { factory_1 as factory };
        let quoter_1: string;
        export { quoter_1 as quoter };
    }
    export { arbitrum_3 as arbitrum };
    export namespace optimism_3 {
        let factory_2: string;
        export { factory_2 as factory };
        let quoter_2: string;
        export { quoter_2 as quoter };
    }
    export { optimism_3 as optimism };
    export namespace polygon_3 {
        let factory_3: string;
        export { factory_3 as factory };
        let quoter_3: string;
        export { quoter_3 as quoter };
    }
    export { polygon_3 as polygon };
    export namespace base_3 {
        let factory_4: string;
        export { factory_4 as factory };
        let quoter_4: string;
        export { quoter_4 as quoter };
    }
    export { base_3 as base };
}
export namespace PUBLIC_RPCS {
    let ethereum_4: string[];
    export { ethereum_4 as ethereum };
    let base_4: string[];
    export { base_4 as base };
    let arbitrum_4: string[];
    export { arbitrum_4 as arbitrum };
    let optimism_4: string[];
    export { optimism_4 as optimism };
    let polygon_4: string[];
    export { polygon_4 as polygon };
    export let bsc: string[];
    export let avalanche: string[];
}
import { ethers } from "ethers";
import * as btc from "@scure/btc-signer";
export { ethers, btc };

/** Chains with a Uniswap v3 QuoterV2 configured (keys of UNIV3). */
export type UniV3Chain = keyof typeof UNIV3;
/** Chains with a Blockscout instance (keys of BLOCKSCOUT). */
export type BlockscoutChain = keyof typeof BLOCKSCOUT;
/** Input to safeTx(): only `to` is required; numeric fields accept decimal strings, numbers or bigints. */
export interface SafeTxInput { to: string; value?: string | number | bigint; data?: string; operation?: 0 | 1 | number; safeTxGas?: string | number | bigint; baseGas?: string | number | bigint; gasPrice?: string | number | bigint; gasToken?: string; refundReceiver?: string; nonce?: string | number | bigint }
/** Normalised Safe transaction (output of safeTx()). */
export interface SafeTx { to: string; value: bigint; data: string; operation: number; safeTxGas: bigint; baseGas: bigint; gasPrice: bigint; gasToken: string; refundReceiver: string; nonce: bigint }
/** One call in a Safe MultiSend batch. */
export interface MultiSendTx { to: string; value?: string | number | bigint; data?: string; operation?: 0 | 1 }
/** EIP-712 typed data (EIP712Domain in `types` is ignored). */
export interface TypedData { types: Record<string, { name: string; type: string }[]>; domain: Record<string, unknown>; message: Record<string, unknown>; primaryType?: string }
