// Regenerates types/onchain.d.ts and types/onchain2.d.ts from the JS sources (tsc declaration emit + tightening of
// parameter types). types/sdk.d.ts and types/server.d.ts are hand-written. Run: npm run types
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const out = mkdtempSync(join(tmpdir(), "bl-dts-"));
const dest = process.argv.includes("--out") ? process.argv[process.argv.indexOf("--out") + 1] : "types";
execFileSync(process.execPath, ["node_modules/typescript/bin/tsc", "src/onchain.js", "src/onchain2.js", "--allowJs", "--declaration", "--emitDeclarationOnly",
  "--outDir", out, "--target", "es2022", "--module", "nodenext", "--moduleResolution", "nodenext", "--skipLibCheck"], { stdio: "inherit" });

const STR = ["sig", "signature", "safe", "address", "addr", "token", "owner", "hash", "data", "message", "topic0", "sel", "tokenIn", "tokenOut", "spender",
  "salt", "initCode", "privateKey", "url", "name", "input", "method", "digest", "contract", "deployer", "a", "b", "tool"];
const tighten = (src, chainType) => src.split("\n").map((line) => {
  if (!/^export (declare )?function /.test(line)) return line;
  let l = line.replace(/\bchain: any\b/g, `chain: ${chainType(line)}`).replace(/\bsigHint: any\b/g, "sigHint?: string")
    .replace(/\bslot: any\b/g, "slot: string | number | bigint").replace(/\bamountIn: any\b/g, "amountIn: string");
  for (const n of STR) l = l.replace(new RegExp(`([(,] ?)${n}: any\\b`, "g"), `$1${n}: string`);
  return l;
}).join("\n");
// Per-function parameter types (checked against the implementations in src/).
const NUM = "string | number | bigint";
const FN = {
  prices: { ids: "string[]" }, feeCost: { f: "{ baseFeeWei?: bigint; tipWei?: Record<string, bigint>; gasPriceWei?: bigint }", gasUnits: NUM },
  convertUnits: { value: "string | number", from: "keyof typeof UNITS" }, encodeCall: { args: "unknown[]" },
  merkleStandard: { types: "string[]", rows: "unknown[][]" }, merkleSimple: { leaves: "string[]" },
  mappingSlot: { keyType: "string", key: "unknown" }, nestedMappingSlot: { keys: "[keyType: string, key: unknown][]" }, arrayElementSlot: { index: NUM },
  erc7201Slot: { id: "string" }, utm: { path: "string" }, chainById: { id: "number | string" },
  multicall: { calls: "{ target: string; data: string }[]" }, safeTx: { p: "SafeTxInput" }, safeTxHash: { chainId: "number | bigint", tx: "SafeTx" },
  safeTxHashOnchain: { tx: "SafeTx" }, encodeMultiSend: { txs: "MultiSendTx[]" }, decodeMultiSend: { calldata: "string" },
  typedDataHash: { td: "TypedData" }, signTypedData: { td: "TypedData" }, recoverTypedData: { td: "TypedData" }, sparkSVG: { values: "(number | null)[]" },
  approvals: { tokens: "{ address: string; symbol?: string; decimals?: number }[]" }, ensBulk: { names: "string[]" }, solRpc: { params: "unknown[]" },
  vanityDifficulty: { pattern: "string" }, findSandwiches: { blockNumber: "number | bigint" }, rpcHealth: { "urls?": "string[]" },
};
const perFn = (src) => src.split("\n").map((line) => {
  const m = line.match(/^export (?:declare )?function ([A-Za-z0-9_]+)\(/); if (!m || !FN[m[1]]) return line;
  let l = line; for (const [k, t] of Object.entries(FN[m[1]])) l = l.replace(new RegExp(`([(,] ?)${k.replace("?", "\\?")}: any\\b`), `$1${k}${k.endsWith("?") ? "" : ""}: ${t}`).replace(`${k}?: any`, `${k}: ${t}`);
  return l;
}).join("\n");
const header = (f) => `// Generated by scripts/gen-types.mjs from src/${f}.js. Do not edit by hand; run \`npm run types\`.\n`;

let a = readFileSync(join(out, "onchain.d.ts"), "utf8");
a = perFn(tighten(a, () => "Chain")) + "\n/** EVM chains supported by the live tools (keys of CHAINS). */\nexport type Chain = keyof typeof CHAINS;\n";
writeFileSync(join(dest, "onchain.d.ts"), header("onchain") + a);

let b = readFileSync(join(out, "onchain2.d.ts"), "utf8");
b = perFn(tighten(b, (line) => (/^export (declare )?function priceImpact\(/.test(line) ? "UniV3Chain" : "Chain")));
b = `import type { Chain } from "./onchain.js";\n` + b + "\n/** Chains with a Uniswap v3 QuoterV2 configured (keys of UNIV3). */\nexport type UniV3Chain = keyof typeof UNIV3;\n/** Chains with a Blockscout instance (keys of BLOCKSCOUT). */\nexport type BlockscoutChain = keyof typeof BLOCKSCOUT;\n" +
  "/** Input to safeTx(): only `to` is required; numeric fields accept decimal strings, numbers or bigints. */\n" +
  "export interface SafeTxInput { to: string; value?: string | number | bigint; data?: string; operation?: 0 | 1 | number; safeTxGas?: string | number | bigint; baseGas?: string | number | bigint; gasPrice?: string | number | bigint; gasToken?: string; refundReceiver?: string; nonce?: string | number | bigint }\n" +
  "/** Normalised Safe transaction (output of safeTx()). */\n" +
  "export interface SafeTx { to: string; value: bigint; data: string; operation: number; safeTxGas: bigint; baseGas: bigint; gasPrice: bigint; gasToken: string; refundReceiver: string; nonce: bigint }\n" +
  "/** One call in a Safe MultiSend batch. */\n" +
  "export interface MultiSendTx { to: string; value?: string | number | bigint; data?: string; operation?: 0 | 1 }\n" +
  "/** EIP-712 typed data (EIP712Domain in `types` is ignored). */\n" +
  "export interface TypedData { types: Record<string, { name: string; type: string }[]>; domain: Record<string, unknown>; message: Record<string, unknown>; primaryType?: string }\n";
writeFileSync(join(dest, "onchain2.d.ts"), header("onchain2") + b);
console.log(`${dest}/onchain.d.ts, ${dest}/onchain2.d.ts written`);
