// Blockchain Lab MCP server (stdio). Built by Blockchain Lab — https://blockchainlab.com
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { BlockchainLab, toolLinks } from "./sdk.js";
import * as C from "./onchain.js";
import * as D from "./onchain2.js";

const CHAIN = z.enum(Object.keys(C.CHAINS)).describe("EVM chain: " + Object.keys(C.CHAINS).join(", "));
const ser = (o) => JSON.stringify(o, (k, v) => (typeof v === "bigint" ? v.toString() : v), 2);
const reply = (o) => ({ content: [{ type: "text", text: ser(o) + "\n\n— Built by Blockchain Lab (https://blockchainlab.com)" }] });
const guard = (fn) => async (args) => { try { return reply(await fn(args)); } catch (e) { return { isError: true, content: [{ type: "text", text: `Error: ${e.shortMessage || e.message}` }] }; } };

export const VERSION = "0.3.0";
const ADDR = z.string().regex(/^0x[0-9a-fA-F]{40}$/, "0x-prefixed 20-byte address");
const HASH = z.string().regex(/^0x[0-9a-fA-F]{64}$/);
const BS_CHAIN = z.enum(Object.keys(D.BLOCKSCOUT));
const V3_CHAIN = z.enum(Object.keys(D.UNIV3));
export function createServer(opts = {}) {
  const bl = new BlockchainLab(opts);
  const s = new McpServer({ name: "blockchainlab", version: VERSION });
  const ro = { readOnlyHint: true, openWorldHint: true };

  s.registerTool("search_whitepapers", { title: "Search whitepapers", description: "Search Blockchain Lab's research corpus (600+ blockchain whitepapers) by text, topic or year. Returns metadata + original source + blockchainlab.com link.", inputSchema: { query: z.string().optional(), topic: z.string().optional(), year: z.number().int().optional(), limit: z.number().int().min(1).max(50).optional() }, annotations: ro }, guard((a) => bl.searchWhitepapers(a)));
  s.registerTool("get_chain", { title: "Find EVM chain", description: "Look up an EVM chain by chain ID, short name or name: native currency, public RPCs, explorers (chainid.network).", inputSchema: { query: z.string() }, annotations: ro }, guard(({ query }) => bl.findChain(query)));
  s.registerTool("top_defi_protocols", { title: "Top DeFi protocols by TVL", description: "Top DeFi protocols by TVL in USD from DefiLlama (nightly snapshot), optionally filtered by category (e.g. Lending, Dexs, Liquid Staking) or chain.", inputSchema: { limit: z.number().int().min(1).max(100).optional(), category: z.string().optional(), chain: z.string().optional() }, annotations: ro }, guard((a) => bl.topProtocols(a)));
  s.registerTool("chains_tvl", { title: "DeFi TVL by chain", description: "DeFi TVL ranking by chain (DefiLlama nightly snapshot).", inputSchema: { limit: z.number().int().min(1).max(100).optional() }, annotations: ro }, guard((a) => bl.chainsTvl(a)));
  s.registerTool("list_hackathons", { title: "Blockchain hackathons", description: "Open and upcoming blockchain hackathons (Devpost, ETHGlobal) from the Blockchain Lab feeds.", inputSchema: {}, annotations: ro }, guard(() => bl.hackathons()));
  s.registerTool("list_events", { title: "Blockchain events", description: "Upcoming blockchain events from the Blockchain Lab feeds.", inputSchema: {}, annotations: ro }, guard(() => bl.events()));
  s.registerTool("list_grants", { title: "Grant programmes", description: "Directory of blockchain ecosystem grant programmes with official links (link status re-checked nightly).", inputSchema: { ecosystem: z.string().optional() }, annotations: ro }, guard((a) => bl.grants(a)));
  s.registerTool("glossary", { title: "Blockchain glossary", description: "Plain-language definitions from blockchainlab.com. Omit term to list all terms.", inputSchema: { term: z.string().optional() }, annotations: ro }, guard(({ term }) => bl.glossary(term)));
  s.registerTool("lookup_standard", { title: "EIP / ERC / BIP lookup", description: "Find an Ethereum EIP/ERC or Bitcoin BIP by number (e.g. 'ERC-4337', '1559', 'BIP-341') or title words.", inputSchema: { query: z.string(), kind: z.enum(["eips", "ercs", "bips"]).optional() }, annotations: ro }, guard(({ query, kind }) => bl.standard(kind, query)));

  s.registerTool("gas_prices", { title: "Live gas / fees", description: "Live fees from public RPCs: EVM base fee + priority tips (eth_feeHistory) and cost in native token + USD for a given gas amount; or Bitcoin sat/vB; or Solana priority fees.", inputSchema: { chain: z.enum([...Object.keys(C.CHAINS), "bitcoin", "solana"]), gasUnits: z.number().int().positive().optional() }, annotations: ro }, guard(async ({ chain, gasUnits = 21000 }) => {
    if (chain === "bitcoin") return { chain, satPerVbyte: await C.btcFees(), source: "mempool.space" };
    if (chain === "solana") return { chain, ...(await C.solFees()), source: "Solana RPC getRecentPrioritizationFees" };
    const f = await C.evmFees(chain); const cost = C.feeCost(f, gasUnits); const px = (await C.prices([C.CHAINS[chain].gecko]))[C.CHAINS[chain].gecko];
    const nat = Number(C.ethers.formatEther(cost.totalWei));
    return { chain, baseFeeGwei: f.baseFeeWei !== undefined ? C.ethers.formatUnits(f.baseFeeWei, "gwei") : null, tipGwei: f.tipWei ? Object.fromEntries(Object.entries(f.tipWei).map(([k, v]) => [k, C.ethers.formatUnits(v, "gwei")])) : null, gasPriceGwei: C.ethers.formatUnits(f.gasPriceWei, "gwei"), gasUnits, costNative: nat, nativeSymbol: C.CHAINS[chain].symbol, costUsd: px ? nat * px : null, priceSource: "DefiLlama coins API", note: C.CHAINS[chain].l2 ? "L2 execution fee only; rollups add an L1 data fee." : undefined };
  }));
  s.registerTool("decode_transaction", { title: "Decode transaction", description: "Fetch and decode a transaction by hash: status, fees, decoded function call + args, decoded event logs.", inputSchema: { chain: CHAIN, hash: z.string().regex(/^0x[0-9a-fA-F]{64}$/) }, annotations: ro }, guard(async ({ chain, hash }) => ({ ...(await C.decodeTx(chain, hash)), view: toolLinks.tx(chain, hash) })));
  s.registerTool("inspect_address", { title: "Inspect address / ENS", description: "Resolve ENS, validate checksum, and inspect an address on a chain: balance, nonce, contract/EOA, proxy implementation, EIP-7702 delegation, ERC-20 metadata.", inputSchema: { address: z.string().describe("0x address or ENS name"), chain: CHAIN.optional() }, annotations: ro }, guard(async ({ address, chain = "ethereum" }) => {
    let addr = address.trim(); let ens = null;
    if (!addr.startsWith("0x")) { ens = addr; addr = await C.resolveEns(addr); if (!addr) throw new Error("ENS name does not resolve"); }
    const chk = C.checkAddress(addr); if (!chk.valid) throw new Error("Invalid address");
    const info = await C.addressInfo(chain, chk.checksum);
    const erc20 = info.isContract && !info.eip7702DelegatesTo ? await C.erc20Meta(chain, chk.checksum) : null;
    return { input: address, ens, address: chk.checksum, inputChecksumValid: chk.inputChecksumValid, primaryName: await C.reverseEns(chk.checksum).catch(() => null), ...info, balance: C.ethers.formatEther(info.balanceWei) + " " + C.CHAINS[chain].symbol, erc20: erc20?.symbol ? erc20 : null, view: toolLinks.address(chk.checksum, chain) };
  }));
  s.registerTool("decode_calldata", { title: "Decode calldata", description: "Decode EVM calldata; looks up the 4-byte selector in openchain/4byte unless a signature is given.", inputSchema: { data: z.string(), signature: z.string().optional() }, annotations: ro }, guard(({ data, signature }) => C.decodeCalldata(data, signature)));
  s.registerTool("abi_utils", { title: "Selector / encode", description: "Compute a function selector & event topic for a signature, and optionally ABI-encode a call with args.", inputSchema: { signature: z.string(), args: z.array(z.any()).optional() }, annotations: { readOnlyHint: true } }, guard(({ signature, args }) => ({ canonical: C.normSig(signature), selector: C.selector(signature), topic: C.topic(signature), calldata: args ? C.encodeCall(signature, args) : undefined })));
  s.registerTool("convert_units", { title: "Convert units", description: "Exact conversion between wei/gwei/ether, sat/btc, lamport/sol.", inputSchema: { value: z.string(), unit: z.enum(Object.keys(C.UNITS)) }, annotations: { readOnlyHint: true } }, guard(({ value, unit }) => C.convertUnits(value, unit)));
  s.registerTool("storage_slot", { title: "Storage slot", description: "Compute a Solidity storage slot (mapping, nested mapping, array element, ERC-7201 namespace) and optionally read it live.", inputSchema: { kind: z.enum(["mapping", "array", "erc7201"]), slot: z.string().optional(), keys: z.array(z.tuple([z.string(), z.string()])).optional().describe("[[type,value],...] for mapping"), index: z.string().optional(), namespace: z.string().optional(), read: z.object({ chain: CHAIN, address: z.string() }).optional() }, annotations: ro }, guard(async (a) => {
    const slot = a.kind === "mapping" ? C.nestedMappingSlot(a.keys || [], a.slot || "0") : a.kind === "array" ? C.arrayElementSlot(a.slot || "0", a.index || "0") : C.erc7201Slot(a.namespace || "");
    return { slot, value: a.read ? await C.readSlot(a.read.chain, a.read.address, slot) : undefined };
  }));
  // ===== v0.2: data (Open Data API v1.1) =====
  s.registerTool("stablecoins", { title: "Stablecoins", description: "Stablecoins by circulating supply with price vs peg, mechanism and 1d/7d/30d supply change (DefiLlama nightly). Filter by symbol or peg type (peggedUSD, peggedEUR…).", inputSchema: { symbol: z.string().optional(), peg: z.string().optional(), limit: z.number().int().min(1).max(100).optional() }, annotations: ro }, guard((a) => bl.stablecoins(a)));
  s.registerTool("defi_yields", { title: "DeFi yields", description: "Top DeFi yield pools (TVL ≥ $10m) with APY, base/reward split and IL risk (DefiLlama nightly). Filter by chain, project, stablecoin-only; sort by tvl or apy.", inputSchema: { chain: z.string().optional(), project: z.string().optional(), stablecoinOnly: z.boolean().optional(), minTvlUsd: z.number().optional(), sort: z.enum(["tvl", "apy"]).optional(), limit: z.number().int().min(1).max(100).optional() }, annotations: ro }, guard((a) => bl.yields(a)));
  s.registerTool("bridges_tvl", { title: "Bridges by TVL", description: "Cross-chain and canonical bridges ranked by TVL (DefiLlama bridge categories), optionally filtered by chain.", inputSchema: { chain: z.string().optional(), limit: z.number().int().min(1).max(100).optional() }, annotations: ro }, guard((a) => bl.bridges(a)));
  s.registerTool("dex_volumes", { title: "DEX volumes", description: "DEX trading volume by protocol (24h/7d/30d) plus market totals (DefiLlama nightly).", inputSchema: { chain: z.string().optional(), limit: z.number().int().min(1).max(100).optional() }, annotations: ro }, guard((a) => bl.volumes("dex-volumes", a)));
  s.registerTool("protocol_fees", { title: "Protocol fees", description: "Protocol fees by protocol (24h/7d/30d) plus totals (DefiLlama nightly).", inputSchema: { chain: z.string().optional(), limit: z.number().int().min(1).max(100).optional() }, annotations: ro }, guard((a) => bl.volumes("fees", a)));
  s.registerTool("l2_metrics", { title: "L2 metrics (L2BEAT)", description: "Ethereum L2/L3 projects: stage, category, stack, risk summary and Total Value Secured breakdown (L2BEAT nightly). Query by name/id/stack, filter by stage ('Stage 0', 'Stage 1', 'Stage 2').", inputSchema: { query: z.string().optional(), stage: z.string().optional(), limit: z.number().int().min(1).max(100).optional() }, annotations: ro }, guard((a) => bl.l2s(a)));
  s.registerTool("security_incidents", { title: "Hacks & exploits", description: "Public record of crypto hacks/exploits (DefiLlama hacks DB): search by protocol/technique, filter by date (YYYY-MM-DD), min USD lost, chain. Returns matches and total lost.", inputSchema: { query: z.string().optional(), since: z.string().optional(), minUsd: z.number().optional(), chain: z.string().optional(), limit: z.number().int().min(1).max(100).optional() }, annotations: ro }, guard((a) => bl.incidents(a)));
  s.registerTool("sanctions_check", { title: "OFAC sanctions check", description: "Check addresses (any chain) against the OFAC SDN digital-currency address list (nightly, via 0xB10C). Screening aid only.", inputSchema: { addresses: z.array(z.string()).min(1).max(200) }, annotations: ro }, guard(({ addresses }) => bl.sanctions(addresses)));
  s.registerTool("get_dataset", { title: "Raw dataset", description: "Fetch any Blockchain Lab Open Data API dataset by name (see the catalogue): returns rows (optionally limited) plus generation time and source.", inputSchema: { name: z.string().describe("e.g. chains, protocols, stablecoins, yields, bridges, dex-volumes, fees, l2-metrics, security-incidents, sanctioned-addresses, rpc-health, eips, ercs, bips, grants, glossary, whitepapers, hackathons, events"), limit: z.number().int().min(1).max(500).optional() }, annotations: ro }, guard(async ({ name, limit = 50 }) => { const d = await bl.dataset(name); return { dataset: name, generated_at: d.generated_at, source: d.source_url, count: d.count, data: Array.isArray(d.data) ? d.data.slice(0, limit) : d.data }; }));

  // ===== v0.2: live tools (pack 2, shared with blockchainlab-tools) =====
  s.registerTool("safe_info", { title: "Safe multisig info", description: "Read a Safe (Gnosis Safe) multisig: owners, threshold, nonce, version.", inputSchema: { chain: CHAIN, safe: ADDR }, annotations: ro }, guard(async ({ chain, safe }) => ({ ...(await D.safeInfo(chain, safe)), view: toolLinks.safe(chain, safe) })));
  s.registerTool("safe_tx_hash", { title: "Safe tx hash", description: "Compute the EIP-712 safeTxHash for a Safe transaction locally and cross-check it with the Safe's on-chain getTransactionHash(). Use to verify what a signer should see on their hardware wallet.", inputSchema: { chain: CHAIN, safe: ADDR, to: ADDR, value: z.string().optional(), data: z.string().optional(), operation: z.number().int().min(0).max(1).optional(), nonce: z.number().int().optional().describe("defaults to the Safe's current nonce") }, annotations: ro }, guard(async (a) => { const info = await D.safeInfo(a.chain, a.safe); const tx = D.safeTx({ ...a, nonce: a.nonce ?? info.nonce }); const l = D.safeTxHash(C.CHAINS[a.chain].id, a.safe, tx, info.version); const onchain = await D.safeTxHashOnchain(a.chain, a.safe, tx); return { ...l, onchainHash: onchain, matches: onchain === l.safeTxHash, tx, safeVersion: info.version }; }));
  s.registerTool("decode_safe_calldata", { title: "Decode Safe calldata", description: "Decode Safe execTransaction (incl. signature types) or MultiSend batch calldata, decoding each inner call.", inputSchema: { data: z.string() }, annotations: ro }, guard(({ data }) => D.decodeSafeCalldata(data)));
  s.registerTool("eip712_hash", { title: "EIP-712 hash / verify", description: "Hash EIP-712 typed data (digest, domain separator, struct hash) and, if a signature is given, recover the signer; optionally check ERC-1271 isValidSignature on a smart account.", inputSchema: { typedData: z.object({ types: z.record(z.any()), domain: z.record(z.any()), message: z.record(z.any()), primaryType: z.string().optional() }), signature: z.string().optional(), erc1271: z.object({ chain: CHAIN, account: ADDR }).optional() }, annotations: ro }, guard(async ({ typedData, signature, erc1271 }) => { const h = D.typedDataHash(typedData); const out = { ...h }; if (signature) { try { out.recoveredSigner = D.recoverTypedData(typedData, signature); } catch (e) { out.recoverError = e.message; } if (erc1271) out.erc1271 = await D.erc1271(erc1271.chain, erc1271.account, h.digest, signature); } return out; }));
  s.registerTool("verify_message", { title: "Verify personal_sign", description: "Recover the signer of an EIP-191 personal_sign message.", inputSchema: { message: z.string(), signature: z.string() }, annotations: { readOnlyHint: true } }, guard(({ message, signature }) => ({ signer: D.recoverPersonal(message, signature), hash: C.ethers.hashMessage(message) })));
  s.registerTool("calldata_diff", { title: "Calldata diff", description: "Decode two calldata blobs and list every argument and 32-byte word that differs (review multisig/governance payloads).", inputSchema: { a: z.string(), b: z.string(), signature: z.string().optional() }, annotations: ro }, guard(({ a, b, signature }) => D.calldataDiff(a, b, signature)));
  s.registerTool("contract_verification", { title: "Contract verification", description: "Is a contract's source verified? Checks Sourcify (full/partial match) and Blockscout (name, compiler, licence, proxy + implementations).", inputSchema: { chain: CHAIN, address: ADDR }, annotations: ro }, guard(async ({ chain, address }) => ({ ...(await D.verification(chain, address)), view: toolLinks.verify(chain, address) })));
  s.registerTool("gas_history", { title: "Gas history", description: "Base fee / median tip / gas-used ratio over the last N (≤1024) blocks with min/median/p75/max stats. Returns stats plus a downsampled series.", inputSchema: { chain: CHAIN, blocks: z.number().int().min(10).max(1024).optional() }, annotations: ro }, guard(async ({ chain, blocks = 1024 }) => { const g = await D.gasHistory(chain, blocks); const step = Math.max(1, Math.floor(g.points.length / 64)); return { chain, from: g.from, to: g.to, stats: g.stats, series: g.points.filter((_, i) => i % step === 0) }; }));
  s.registerTool("bridge_quotes", { title: "Bridge fee compare", description: "Live bridge quotes for USDC or ETH between Ethereum, Base, Arbitrum, OP, Polygon from Across, LI.FI and Relay: amount received, cost, ETA.", inputSchema: { from: BS_CHAIN, to: BS_CHAIN, asset: z.enum(["USDC", "ETH"]).optional(), amount: z.number().positive() }, annotations: ro }, guard((a) => D.bridgeQuotes(a)));
  s.registerTool("token_approvals", { title: "Token approvals", description: "Which well-known spenders (Permit2, Uniswap routers, 1inch, 0x, CoW, Balancer, OpenSea, Aave…) can spend an address's top ERC-20s; flags unlimited approvals; returns revoke calldata + Revoke.cash link.", inputSchema: { chain: CHAIN, owner: z.string().describe("0x address or ENS") }, annotations: ro }, guard(async ({ chain, owner }) => { if (!owner.startsWith("0x")) owner = await C.resolveEns(owner); const r = await D.approvals(chain, owner); return { ...r, view: toolLinks.approvals(chain, r.owner) }; }));
  s.registerTool("ens_bulk", { title: "ENS bulk resolve", description: "Resolve up to 50 ENS names (address + avatar/url/twitter/github records, primary-name check) or reverse-resolve addresses.", inputSchema: { inputs: z.array(z.string()).min(1).max(50) }, annotations: ro }, guard(({ inputs }) => D.ensBulk(inputs)));
  s.registerTool("decode_solana_tx", { title: "Decode Solana tx", description: "Decode a Solana transaction signature: status, fee, compute units, parsed instructions + inner instructions with program names, SOL and token balance changes.", inputSchema: { signature: z.string().min(60).max(100) }, annotations: ro }, guard(async ({ signature }) => ({ ...(await D.decodeSolTx(signature)), view: toolLinks.solana(signature) })));
  s.registerTool("decode_psbt", { title: "Decode Bitcoin PSBT / tx", description: "Decode a Bitcoin PSBT (base64/hex) or raw tx hex offline: inputs, outputs, addresses, script types, fee, fee rate, signatures, BIP-32 paths.", inputSchema: { psbt: z.string() }, annotations: { readOnlyHint: true } }, guard(({ psbt }) => D.decodePSBT(psbt)));
  s.registerTool("address_labels", { title: "Address labels", description: "Public labels for an EVM address: Blockscout name/tags/token, ENS primary name, token-list match, known spender name, OFAC SDN check.", inputSchema: { chain: BS_CHAIN, address: ADDR }, annotations: ro }, guard(async ({ chain, address }) => ({ ...(await D.addressLabels(chain, address)), view: toolLinks.labels(chain, address) })));
  s.registerTool("vanity_estimate", { title: "Vanity address estimate", description: "Difficulty and expected attempts for an Ethereum vanity prefix (case-insensitive or EIP-55), with time at a given keys/s rate. Also computes a CREATE2 address if deployer+salt+initCode are given.", inputSchema: { prefix: z.string().optional(), caseSensitive: z.boolean().optional(), keysPerSecond: z.number().positive().optional(), create2: z.object({ deployer: ADDR, salt: z.string(), initCode: z.string() }).optional() }, annotations: { readOnlyHint: true } }, guard(({ prefix, caseSensitive, keysPerSecond = 2e8, create2 }) => { const out = {}; if (prefix) { const d = D.vanityDifficulty(prefix, { caseSensitive }); out.vanity = { ...d, keysPerSecond, seconds50: d.attempts50 / keysPerSecond, seconds90: d.attempts90 / keysPerSecond }; } if (create2) out.create2Address = D.create2Address(create2.deployer, create2.salt, create2.initCode); return out; }));
  s.registerTool("uniswap_price_impact", { title: "Uniswap v3 price impact", description: "On-chain Uniswap v3 QuoterV2 quote for a single pool: amount out, mid vs execution price, price impact, price after, ticks crossed, gas estimate.", inputSchema: { chain: V3_CHAIN, tokenIn: ADDR, tokenOut: ADDR, amountIn: z.string().describe("human units, e.g. '10'"), fee: z.number().int().optional().describe("100, 500, 3000 or 10000") }, annotations: ro }, guard(({ chain, tokenIn, tokenOut, amountIn, fee = 500 }) => D.priceImpact(chain, tokenIn, tokenOut, amountIn, fee)));
  s.registerTool("mev_sandwich_check", { title: "MEV sandwich check", description: "Was this swap sandwiched? Looks for a same-pool same-direction front-run and reversing back-run from the same EOA/bot within 8 positions in the block (heuristic).", inputSchema: { chain: CHAIN, hash: HASH }, annotations: ro }, guard(async ({ chain, hash }) => ({ ...(await D.sandwichCheck(chain, hash)), view: toolLinks.mev(chain, hash) })));
  s.registerTool("rpc_health", { title: "Public RPC health", description: "Probe free public RPC endpoints for a chain now (latency, block lag, chain-ID check) and include the nightly server-side snapshot.", inputSchema: { chain: CHAIN }, annotations: ro }, guard(async ({ chain }) => ({ live: await D.rpcHealth(chain), nightly: await bl.rpcHealthSnapshot(chain) })));
  return s;
}

export async function main() {
  const server = createServer({ apiBase: process.env.BLOCKCHAINLAB_API || undefined });
  await server.connect(new StdioServerTransport());
  console.error("Blockchain Lab MCP server running on stdio — https://blockchainlab.com");
}
